version: '3.9'

services:
  app:
    build: .
    container_name: blog_backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/blogdb?schema=public
      - PORT=5000
    depends_on:
      - db
    volumes:
      - .:/app
      - node_modules:/app/node_modules

  db:
    image: postgres:13
    container_name: blogdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blogdb
    ports:
      - "5432:5432"
    volumes:
      - blog_data:/var/lib/postgresql/data

volumes:
  blog_data:
  node_modules:
