version: '3.9'

services:
  app:
    build: .
    container_name: blog_backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/blogdb?schema=public
      - PORT=5000
      - JWT_SECRET_KEY=s3cr3tK3y!9d2#F$kL@7gZx^WmQ%R8vPn

    depends_on:
      - db
    volumes:
      - .:/app:cached

  db:
    image: docker.io/library/postgres:13
    container_name: blog_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blogdb
    ports:
      - "15432:5432"
    volumes:
      - blog_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  blog_data:
